CREATE SCHEMA IF NOT EXISTS MAIN;

SET SCHEMA MAIN;

DROP TABLE Note IF EXISTS;

CREATE TABLE IF NOT EXISTS Note(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    title VARCHAR(500) CHECK (CHAR_LENGTH(title) > 0),
    content VARCHAR(4000)
);

COMMENT ON TABLE Note IS 'Нотатки';
COMMENT ON COLUMN Note.id IS 'ID нотатки';
COMMENT ON COLUMN Note.title IS 'Заголовок нотатки';
COMMENT ON COLUMN Note.content IS 'Зміст нотатки';